services:
  - type: web
    name: interface-project
    env: static
    buildCommand: echo "No build required"
    staticPublishPath: ./
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
        condition: false